version: '3'
services:
  api-node-pg:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Fesa1234
      - POSTGRESQL_DATABASE=study
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
